### ISSUE TITLE
Parametrized figures for more than 9 labels

### ISSUE THREAD

**Issue by emmanuelle-dankwa** [dr-harper/blog#3]
Hi Mike, I'm using your package DiagrammeR and my figure has about 15 labels with R code. I followed the example in the Parametrized figures section of the blog but thins start to break down after 10. The figure gives the same label as [1] and adds a 0. Is there a workaround for this?

**Comment by emmanuelle-dankwa** [comment]
Resolved now.

**Comment by dr-harper** [comment]
Sorry @emmanuelle-dankwa , I missed this issue an have just seen it, almost 2 years too late 😆 glad you fixed it
